Add Limit test to document how the "limit" parameter is supposed to work
ExposuresProvider/cam-kp-api pull request #499
Opened 2022-03-16 18:41 UTC by gaurav

I noticed some odd behavior with the way in which the `limit` parameter works, which can be best summarized by listing the results of running the same query against the SPARQL endpoint using the new test I've written in this PR.

```
Retrieved 14 results when limit=0
Retrieved 1 results when limit=1
Retrieved 2 results when limit=2
Retrieved 2 results when limit=3
Retrieved 2 results when limit=4
Retrieved 3 results when limit=5
Retrieved 6 results when limit=10
Retrieved 13 results when limit=20
Retrieved 14 results when limit=30
Retrieved 14 results when limit=40
Retrieved 14 results when limit=50
Retrieved 14 results when limit=60
Retrieved 14 results when limit=70
Retrieved 14 results when limit=80
Retrieved 14 results when limit=90
Retrieved 14 results when limit=100
```

So: limit=0, 1, 2 seem to work as expected, then limit=3, 4, 5, 10, 20 are off, and thereafter we consistently return 14 results for higher limits. So possibly the limit parameter isn't just a limit on the number of results that could be returned? We never return more than ${limit} results, so it's certainly working correctly.

Given that it's working correctly (if a bit oddly), I'm going to leave this test and PR here as a draft so we can dig into this later if needed. For now, I'm going to continue my other testing work by just setting the limit high enough that we're unlikely to hit into this bug.

2022-04-07 17:29 UTC, gaurav commented
Jim is concerned that this code might also misbehave if:

| s | p | o | stype | ptype |
| -- | -- | -- | ---- | ---- |
| 1 | p1 | 2 | A | B |
| 1 | p1 | 2 | C | B |
| 3 | p1 | 4 | A | B |

Note that in this case there are two different individuals that indicate the same relationship (A p1 B). They could be from different sources.

The way to find this would be a unit test that provides tests the difference pieces of the `run()` workflow, e.g. `getTRAPIEdgeBindingsMany()`.

2022-07-01 14:50 UTC, balhoff requested changes
Looks, good, just a few possible changes.

2022-07-01 14:50 UTC, balhoff commented on src/main/scala/org/renci/cam/QueryService.scala
> +        }).runCollect
Possibly also remove ZIO stuff here, just map/flatMap over results.

2022-07-01 14:50 UTC, balhoff commented on src/main/scala/org/renci/cam/QueryService.scala
> +  }
I think this whole method can be non-ZIO.

2022-07-01 14:50 UTC, balhoff commented on src/main/scala/org/renci/cam/QueryService.scala
> +  }
Return a `List[TRAPIResult]`.

2022-07-05 15:31 UTC, gaurav commented on src/main/scala/org/renci/cam/QueryService.scala
> +        .runCollect
Fixed in e263139fda9.

2022-07-07 17:11 UTC, merged